engines:
  duplication:
    enabled: true
    config:
      languages:
      - php
  fixme:
    enabled: false
  phpcodesniffer:
    enabled: true
  phpmd:
    enabled: true

ratings:
  paths:
  - "**.php"

exclude_paths:
- test/**/*