language: php

jobs:
  include:
    - php: 5.4
      dist: trusty
    - php: 5.5
      dist: trusty
    - php: 5.6
      dist: xenial
    - php: 7.0
      dist: xenial
    - php: 7.1
      dist: xenial
    - php: 7.2
      dist: xenial
    - php: 7.3
      dist: xenial
    - php: 7.4
      dist: xenial
#    - php: 8.0 note: not working, since php8 phpunit requires rewrite which is incomatible with php 5.*
#      dist: focal
    
before_script:
  - phpenv config-add test/resources/php.ini

install:
  - composer install || composer install --ignore-platform-reqs

script:
  - vendor/bin/phing travis

after_script:
  - travis_retry php vendor/bin/coveralls -v
  - vendor/bin/test-reporter

addons:
  code_climate:
    repo_token: 5d81d5163c7f9b810b46451042cb0069d24c91a5887466ba774bf89a56f0187e
