<?php
/**
 * This class will test some events.
 *
 * PHP Version 5
 *
 * @category   Pami
 * @package    Test
 * @subpackage Event
 * @author     Marcelo Gornstein <marcelog@gmail.com>
 * @license    http://marcelog.github.com/ Apache License 2.0
 * @version    SVN: $Id$
 * @link       http://marcelog.github.com/
 *
 * Copyright 2011 Marcelo Gornstein <marcelog@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

namespace Tests;

use Mockery;
use PAMI\Stream\Stream;
use PAMI\Client\Impl\ClientImpl;
use Tests\Resources\SomeListenerClass;
use Mockery\Adapter\Phpunit\MockeryTestCase;

/**
 * This class will test some events.
 *
 * PHP Version 5
 *
 * @category   Pami
 * @package    Test
 * @subpackage Event
 * @author     Marcelo Gornstein <marcelog@gmail.com>
 * @license    http://marcelog.github.com/ Apache License 2.0
 * @link       http://marcelog.github.com/
 */
class EventsTest extends MockeryTestCase
{
    protected string $microTime;

    public function setUp(): void
    {
        parent::setUp();

        $this->microTime = (string)microtime(true);
        setMockedMicroTime($this->microTime);
    }

    public function testCanReportEvents(): void
    {
        $eventNames            = [
            'AsyncAGI',
            'AGIExec',
            'VarSet',
            'Unlink',
            'vgsm_sms_rx',
            'vgsm_net_state',
            'vgsm_me_state',
            'DTMF',
            'Bridge',
            'VoicemailUserEntryComplete',
            'StatusComplete',
            'ParkedCallsComplete',
            'DBGetResponse',
            'VoicemailUserEntry',
            'Transfer',
            'Status',
            'ShowDialPlanComplete',
            'Rename',
            'RegistrationsComplete',
            'RTPSenderStat',
            'RTPReceiverStat',
            'RTCPSent',
            'RTCPReceiverStat',
            'RTCPReceived',
            'QueueSummaryComplete',
            'QueueStatusComplete',
            'DAHDIShowChannelsComplete',
            'QueueSummary',
            'QueueParams',
            'QueueMemberStatus',
            'QueueMemberRemoved',
            'QueueMemberPaused',
            'QueueMember',
            'QueueMemberAdded',
            'PeerlistComplete',
            'PeerStatus',
            'PeerEntry',
            'OriginateResponse',
            'Newstate',
            'Newexten',
            'Newchannel',
            'NewCallerid',
            'NewAccountCode',
            'MusicOnHold',
            'MessageWaiting',
            'Masquerade',
            'ListDialplan',
            'Leave',
            'Join',
            'Hold',
            'Hangup',
            'ExtensionStatus',
            'Dial',
            'DAHDIShowChannels',
            'CoreShowChannelsComplete',
            'CoreShowChannel',
            'ChannelUpdate',
            'Agents',
            'AgentsComplete',
            'Agentlogoff',
            'Agentlogin',
            'AgentConnect',
            'DongleSMSStatus',
            'FullyBooted',
            'DongleShowDevicesComplete',
            'DongleDeviceEntry',
            'DongleNewUSSDBase64',
            'DongleNewUSSD',
            'DongleUSSDStatus',
            'DongleNewCUSD',
            'DongleStatus',
            'CEL',
            'JabberEvent',
            'Registry',
            'UserEvent',
            'ParkedCall',
            'UnParkedCall',
            'Link',
            'AGIExecStart',
            'AGIExecEnd',
            'AsyncAGIStart',
            'AsyncAGIExec',
            'AsyncAGIEnd',
            'QueueCallerJoin',
            'QueueCallerLeave',
            'AttendedTransfer',
            'BlindTransfer',
            'DialBegin',
            'DialEnd',
            'DTMFBegin',
            'DTMFEnd',
            'BridgeCreate',
            'BridgeDestroy',
            'BridgeEnter',
            'BridgeLeave',
            'MusicOnHoldStart',
            'MusicOnHoldStop',
            'ConfbridgeStart',
            'ConfbridgeEnd',
            'ConfbridgeJoin',
            'ConfbridgeLeave',
            'ConfbridgeMute',
            'ConfbridgeUnmute',
            'ConfbridgeTalking',
            'ConfbridgeList',
            'ConfbridgeListComplete',
            'BridgeInfoChannel',
            'BridgeInfoComplete',
        ];
        $eventTranslatedValues = [
            'QueueMemberStatus' => [
                'Paused' => true,
            ],
            'QueueMemberPaused' => [
                'Paused' => true,
            ],
            'QueueMember'       => [
                'Paused' => true,
            ],
            'QueueMemberAdded'  => [
                'Paused' => true,
            ],
        ];
        $eventValues           = [
            'UserEvent'                  => [
                'Privilege' => 'Privilege',
                'UniqueID'  => 'UniqueID',
                'UserEvent' => 'UserEvent',
            ],
            'Registry'                   => [
                'Channel' => 'Channel',
                'Domain' => 'Domain',
                'Status' => 'Status',
            ],
            'JabberEvent'                => [
                'Privilege' => 'Privilege',
                'Account' => 'Account',
                'Packet' => 'Packet',
            ],
            'AsyncAGI'                   => [
                'Env'     => 'Env',
                'Channel' => 'Channel',
                'CommandId' => 'CommandId',
                'Privilege' => 'Privilege',
                'SubEvent' => 'SubEvent',
                'Result'  => 'Result',
            ],
            'FullyBooted'                => [],
            'DongleUSSDStatus'           => [
                'Privilege' => 'Privilege',
                'Id'     => 'Id',
                'Device' => 'Device',
                'Status' => 'Status',
            ],
            'DongleNewUSSDBase64'        => [
                'Device'    => 'Device',
                'Message'   => 'Message',
                'Privilege' => 'Privilege',
            ],
            'DongleNewCUSD'              => [
                'Device'    => 'Device',
                'Message'   => 'Message',
                'Privilege' => 'Privilege',
            ],
            'DongleNewUSSD'              => [
                'Device'    => 'Device',
                'LineCount' => 'LineCount',
                'Privilege' => 'Privilege',
            ],
            'DongleDeviceEntry'          => [
                'Device'             => 'Device',
                'AudioSetting'       => 'AudioSetting',
                'DataSetting'        => 'DataSetting',
                'IMEISetting'        => 'IMEISetting',
                'IMSISetting'        => 'IMSISetting',
                'ChannelLanguage'    => 'ChannelLanguage',
                'Context'            => 'Context',
                'Exten'              => 'Exten',
                'Group'              => 'Group',
                'RXGain'             => 'RXGain',
                'TXGain'             => 'TXGain',
                'U2DIAG'             => 'U2DIAG',
                'UseCallingPres'     => 'UseCallingPres',
                'DefaultCallingPres' => 'DefaultCallingPres',
                'AutoDeleteSMS'      => 'AutoDeleteSMS',
                'DisableSMS'         => 'DisableSMS',
                'ResetDongle'        => 'ResetDongle',
                'SMSPDU'             => 'SMSPDU',
                'CallWaitingSetting' => 'CallWaitingSetting',
                'DTMF'               => 'DTMF',
                'MinimalDTMFGap'     => 'MinimalDTMFGap',
                'MinimalDTMFDuration' => 'MinimalDTMFDuration',
                'MinimalDTMFInterval' => 'MinimalDTMFInterval',
                'State'              => 'State',
                'AudioState'         => 'AudioState',
                'DataState'          => 'DataState',
                'Voice'              => 'Voice',
                'SMS'                => 'SMS',
                'Manufacturer'       => 'Manufacturer',
                'Model'              => 'Model',
                'Firmware'           => 'Firmware',
                'IMEIState'          => 'IMEIState',
                'IMSIState'          => 'IMSIState',
                'GSMRegistrationStatus' => 'GSMRegistrationStatus',
                'RSSI'               => 'RSSI',
                'Mode'               => 'Mode',
                'Submode'            => 'Submode',
                'ProviderName'       => 'ProviderName',
                'LocationAreaCode'   => 'LocationAreaCode',
                'CellID'             => 'CellID',
                'SubscriberNumber'   => 'SubscriberNumber',
                'SMSServiceCenter'   => 'SMSServiceCenter',
                'UseUCS2Encoding'    => 'UseUCS2Encoding',
                'USSDUse7BitEncoding' => 'USSDUse7BitEncoding',
                'USSDUseUCS2Decoding' => 'USSDUseUCS2Decoding',
                'TasksInQueue'       => 'TasksInQueue',
                'CommandsInQueue'    => 'CommandsInQueue',
                'CallWaitingState'   => 'CallWaitingState',
                'CurrentDeviceState' => 'CurrentDeviceState',
                'DesiredDeviceState' => 'DesiredDeviceState',
                'CallsChannels'      => 'CallsChannels',
                'Active'             => 'Active',
                'Held'               => 'Held',
                'Dialing'            => 'Dialing',
                'Alerting'           => 'Alerting',
                'Incoming'           => 'Incoming',
                'Waiting'            => 'Waiting',
                'Releasing'          => 'Releasing',
                'Initializing'       => 'Initializing',
            ],
            'DongleShowDevicesComplete'  => ['ListItems' => 'items'],
            'DongleSMSStatus'            => [
                'Privilege' => 'Privilege',
                'Id'     => 'Id',
                'Device' => 'Device',
                'Status' => 'Status',
            ],
            'DongleStatus'               => [
                'Privilege' => 'Privilege',
                'Device' => 'Device',
                'Status' => 'Status',
            ],
            'AgentConnect'               => [
                'HoldTime'  => 'HoldTime',
                'Privilege' => 'Privilege',
                'BridgedChannel' => 'BridgedChannel',
                'RingTime'  => 'RingTime',
                'Member'    => 'Member',
                'MemberName' => 'MemberName',
                'UniqueID'  => 'UniqueID',
                'Channel'   => 'Channel',
                'Queue'     => 'Queue',
            ],
            'Agentlogoff'                => [
                'Logintime' => 'Logintime',
                'UniqueID' => 'UniqueID',
                'Agent' => 'Agent',
                'Privilege' => 'Privilege',
            ],
            'Agentlogin'                 => [
                'UniqueID' => 'UniqueID',
                'Agent'   => 'Agent',
                'Privilege' => 'Privilege',
                'Channel' => 'Channel',
            ],
            'AgentsComplete'             => [],
            'Agents'                     => [
                'TalkingToChannel' => 'TalkingToChannel',
                'TalkingTo' => 'TalkingTo',
                'LoggedInTime' => 'LoggedInTime',
                'LoggedInChan' => 'LoggedInChan',
                'Name'      => 'Name',
                'Status'    => 'Status',
                'Agent'     => 'Agent',
            ],
            'ChannelUpdate'              => [
                'Privilege' => 'Privilege',
                'Channel'   => 'Channel',
                'ChannelType' => 'ChannelType',
                'UniqueID'  => 'UniqueID',
                'SIPfullcontact' => 'SIPfullcontact',
                'SIPcallid' => 'SIPcallid',
            ],
            'CoreShowChannel'            => [
                'UniqueID'       => 'UniqueID',
                'Privilege'      => 'Privilege',
                'Channel'        => 'Channel',
                'AccountCode'    => 'AccountCode',
                'Priority'       => 'Priority',
                'Extension'      => 'Extension',
                'Context'        => 'Context',
                'CallerIDNum'    => 'CallerIDNum',
                'ChannelStateDesc' => 'ChannelStateDesc',
                'ChannelState'   => 'ChannelState',
                'ApplicationData' => 'ApplicationData',
                'Application'    => 'Application',
                'BridgedUniqueID' => 'BridgedUniqueID',
                'BridgedChannel' => 'BridgedChannel',
                'Duration'       => 'Duration',
            ],
            'DAHDIShowChannels'          => [
                'Channel'    => 'Channel',
                'Context'    => 'Context',
                'Alarm'      => 'Alarm',
                'DND'        => 'DND',
                'SignallingCode' => 'SignallingCode',
                'Signalling' => 'Signalling',
            ],
            'Dial'                       => [
                'Privilege'    => 'Privilege',
                'Destination'  => 'Destination',
                'SubEvent'     => 'SubEvent',
                'CallerIdName' => 'CallerIdName',
                'CallerIdNum'  => 'CallerIdNum',
                'Channel'      => 'Channel',
                'DialStatus'   => 'DialStatus',
                'DialString'   => 'DialString',
                'UniqueID'     => 'UniqueID',
                'DestUniqueID' => 'DestUniqueID',
            ],
            'ExtensionStatus'            => [
                'Privilege' => 'Privilege',
                'Status'  => 'Status',
                'Exten'   => 'Extension',
                'Hint'    => 'Hint',
                'Context' => 'Context',
            ],
            'Hangup'                     => [
                'CallerIdName' => 'CallerIdName',
                'CallerIdNum' => 'CallerIdNum',
                'Channel'   => 'Channel',
                'Privilege' => 'Privilege',
                'UniqueID'  => 'UniqueID',
                'Cause'     => 'Cause',
                'cause-txt' => 'cause-txt',
            ],
            'Hold'                       => [
                'Privilege' => 'Privilege',
                'UniqueID' => 'UniqueID',
                'Status'   => 'Status',
                'Channel'  => 'Channel',
            ],
            'Join'                       => [
                'CallerIdName' => 'CallerIdName',
                'CallerIdNum' => 'CallerIdNum',
                'UniqueID'  => 'UniqueID',
                'Position'  => 'Position',
                'Queue'     => 'Queue',
                'Channel'   => 'Channel',
                'Privilege' => 'Privilege',
                'Count'     => 'Count',
            ],
            'Leave'                      => [
                'Channel'  => 'Channel',
                'Privilege' => 'Privilege',
                'UniqueID' => 'UniqueID',
                'Count'    => 'Count',
                'Queue'    => 'Queue',
            ],
            'ListDialplan'               => [
                'AppData'        => 'AppData',
                'Application'    => 'Application',
                'Priority'       => 'Priority',
                'Extension'      => 'Extension',
                'Context'        => 'Context',
                'Registrar'      => 'Registrar',
                'IncludeContext' => 'IncludeContext',
            ],
            'Masquerade'                 => [
                'OriginalState' => 'OriginalState',
                'Original'  => 'Original',
                'CloneState' => 'CloneState',
                'Clone'     => 'Clone',
                'Privilege' => 'Privilege',
            ],
            'MessageWaiting'             => [
                'Privilege' => 'Privilege',
                'Waiting'   => 'Waiting',
                'Mailbox'   => 'Mailbox',
            ],
            'MusicOnHold'                => [
                'Channel'  => 'Channel',
                'Privilege' => 'Privilege',
                'UniqueID' => 'UniqueID',
                'State'    => 'State',
            ],
            'NewAccountCode'             => [
                'Channel'   => 'Channel',
                'Privilege' => 'Privilege',
                'UniqueID'  => 'UniqueID',
                'AccountCode' => 'AccountCode',
                'OldAccountCode' => 'OldAccountCode',
            ],
            'NewCallerid'                => [
                'UniqueID'        => 'UniqueID',
                'CallerIdName'    => 'CallerIdName',
                'CallerIdNum'     => 'CallerIdNum',
                'Channel'         => 'Channel',
                'Privilege'       => 'Privilege',
                'CID-CallingPres' => 'CID-CallingPres',
            ],
            'Newchannel'                 => [
                'UniqueID'    => 'UniqueID',
                'CallerIdName' => 'CallerIdName',
                'CallerIdNum' => 'CallerIdNum',
                'ChannelStateDesc' => 'ChannelStateDesc',
                'ChannelState' => 'ChannelState',
                'AccountCode' => 'AccountCode',
                'Channel'     => 'Channel',
                'Context'     => 'Context',
                'Exten'       => 'Exten',
                'Privilege'   => 'Privilege',
            ],
            'Newexten'                   => [
                'Channel'  => 'Channel',
                'Privilege' => 'Privilege',
                'AppData'  => 'AppData',
                'Application' => 'Application',
                'Priority' => 'Priority',
                'Extension' => 'Extension',
                'Exten'    => 'Exten',
                'Context'  => 'Context',
                'UniqueID' => 'UniqueID',
            ],
            'Newstate'                   => [
                'CallerIdName'      => 'CallerIdName',
                'CallerIdNum'       => 'CallerIdNum',
                'UniqueID'          => 'UniqueID',
                'ChannelStateDesc'  => 'ChannelStateDesc',
                'ChannelState'      => 'ChannelState',
                'Channel'           => 'Channel',
                'Privilege'         => 'Privilege',
                'ConnectedLineNum'  => 'ConnectedLineNum',
                'ConnectedLineName' => 'ConnectedLineName',
            ],
            'OriginateResponse'          => [
                'CallerIdName' => 'CallerIdName',
                'CallerIdNum' => 'CallerIdNum',
                'Response'  => 'Response',
                'ActionID'  => 'ActionID',
                'UniqueID'  => 'UniqueID',
                'Reason'    => 'Reason',
                'Channel'   => 'Channel',
                'Context'   => 'Context',
                'Exten'     => 'Exten',
                'Privilege' => 'Privilege',
            ],
            'PeerEntry'                  => [
                'RealtimeDevice' => 'RealtimeDevice',
                'Status'      => 'Status',
                'ACL'         => 'ACL',
                'TextSupport' => 'TextSupport',
                'VideoSupport' => 'VideoSupport',
                'NatSupport'  => 'NatSupport',
                'Dynamic'     => 'Dynamic',
                'IPPort'      => 'IPPort',
                'IPAddress'   => 'IPAddress',
                'ChanObjectType' => 'ChanObjectType',
                'ObjectName'  => 'ObjectName',
                'ChannelType' => 'ChannelType',
            ],
            'PeerStatus'                 => [
                'Privilege'  => 'Privilege',
                'ChannelType' => 'ChannelType',
                'Peer'       => 'Peer',
                'PeerStatus' => 'PeerStatus',
            ],
            'QueueMemberRemoved'         => [
                'MemberName' => 'MemberName',
                'Location'  => 'Location',
                'Queue'     => 'Queue',
                'Privilege' => 'Privilege',
            ],
            'QueueMemberPaused'          => [
                'MemberName' => 'MemberName',
                'Location' => 'Location',
                'Queue'    => 'Queue',
                'Privilege' => 'Privilege',
                'Paused'   => 1,
            ],
            'QueueMember'                => [
                'Name'       => 'Name',
                'Location'   => 'Location',
                'Queue'      => 'Queue',
                'Paused'     => 1,
                'Status'     => 'Status',
                'CallsTaken' => 'CallsTaken',
                'Penalty'    => 'Penalty',
                'Membership' => 'Membership',
            ],
            'QueueMemberAdded'           => [
                'MemberName' => 'MemberName',
                'LastCall'   => 'LastCall',
                'Location'   => 'Location',
                'Queue'      => 'Queue',
                'Paused'     => 1,
                'Status'     => 'Status',
                'CallsTaken' => 'CallsTaken',
                'Penalty'    => 'Penalty',
                'Membership' => 'Membership',
                'Privilege'  => 'Privilege',
            ],
            'QueueMemberStatus'          => [
                'Paused'    => 1,
                'Status'    => 'Status',
                'CallsTaken' => 'CallsTaken',
                'Penalty'   => 'Penalty',
                'Membership' => 'Membership',
                'MemberName' => 'MemberName',
                'Location'  => 'Location',
                'Queue'     => 'Queue',
                'Privilege' => 'Privilege',
            ],
            'QueueParams'                => [
                'Completed' => '4',
                'HoldTime'  => '5',
                'Calls'     => '6',
                'Strategy'  => 'Strategy',
                'Max'       => '6',
                'Queue'     => 'Queue',
                'Weight'    => '2',
                'ServiceLevelPerf' => 'ServiceLevelPerf',
                'ServiceLevel' => '1',
                'Abandoned' => '3',
            ],
            'QueueSummaryComplete'       => [],
            'QueueSummary'               => [
                'LongestHoldTime' => 'LongestHoldTime',
                'HoldTime' => 'HoldTime',
                'Callers'  => 'Callers',
                'Available' => 'Available',
                'LoggedIn' => 'LoggedIn',
                'Queue'    => 'Queue',
            ],
            'QueueStatusComplete'        => [],
            'DAHDIShowChannelsComplete'  => ['items' => 'ListItems'],
            'PeerlistComplete'           => ['ListItems' => 'ListItems'],
            'CoreShowChannelsComplete'   => ['ListItems' => 'ListItems'],
            'RTCPReceived'               => [
                'DLSR'            => 'DLSR',
                'RTT'             => 'RTT',
                'LastSR'          => 'LastSR',
                'IAJitter'        => 'IAJitter',
                'SequenceNumberCycles' => 'SequenceNumberCycles',
                'HighestSequence' => 'HighestSequence',
                'PacketsLost'     => 'PacketsLost',
                'FractionLost'    => 'FractionLost',
                'SenderSSRC'      => 'SenderSSRC',
                'ReceptionReports' => 'ReceptionReports',
                'PT'              => 'PT',
                'Privilege'       => 'Privilege',
                'From'            => 'From',
            ],
            'RTCPReceiverStat'           => [
                'RRCount'   => 'RRCount',
                'Jitter'    => 'Jitter',
                'LostPackets' => 'LostPackets',
                'ReceivedPackets' => 'ReceivedPackets',
                'SSRC'      => 'SSRC',
                'Privilege' => 'Privilege',
                'Transit'   => 'Transit',
            ],
            'RTCPSent'                   => [
                'DLSR'        => 'DLSR',
                'TheirLastSR' => 'TheirLastSR',
                'IAJitter'    => 'IAJitter',
                'CumulativeLoss' => 'CumulativeLoss',
                'FractionLost' => 'FractionLost',
                'ReportBlock' => 'ReportBlock',
                'SentOctets'  => 'SentOctets',
                'SentPackets' => 'SentPackets',
                'SentRTP'     => 'SentRTP',
                'SentNTP'     => 'SentNTP',
                'OurSSRC'     => 'OurSSRC',
                'To'          => 'To',
                'Privilege'   => 'Privilege',
            ],
            'RTPSenderStat'              => [
                'SRCount'   => 'SRCount',
                'RTT'       => 'RTT',
                'Jitter'    => 'Jitter',
                'LostPackets' => 'LostPackets',
                'SentPackets' => 'SentPackets',
                'SSRC'      => 'SSRC',
                'Privilege' => 'Privilege',
            ],
            'RTPReceiverStat'            => [
                'RRCount'   => 'RRCount',
                'Jitter'    => 'Jitter',
                'LostPackets' => 'LostPackets',
                'ReceivedPackets' => 'ReceivedPackets',
                'SSRC'      => 'SSRC',
                'Privilege' => 'Privilege',
                'Transit'   => 'Transit',
            ],
            'Rename'                     => [
                'UniqueID'  => 'UniqueID',
                'Oldname'   => 'Oldname',
                'Newname'   => 'Newname',
                'Channel'   => 'Channel',
                'Privilege' => 'Privilege',
            ],
            'ShowDialPlanComplete'       => [
                'listcontexts' => 'listcontexts',
                'listpriorities' => 'listpriorities',
                'listextensions' => 'listextensions',
                'listitems' => 'listitems',
                'privilege' => 'privilege',
            ],
            'Status'                     => [
                'BridgedUniqueID' => 'BridgedUniqueID',
                'BridgedChannel' => 'BridgedChannel',
                'Seconds'        => 'Seconds',
                'AccountCode'    => 'AccountCode',
                'Duration'       => 'Duration',
                'CallerIDNum'    => 'CallerIDNum',
                'ApplicationData' => 'ApplicationData',
                'Application'    => 'Application',
                'ChannelStateDesc' => 'ChannelStateDesc',
                'ChannelState'   => 'ChannelState',
                'Priority'       => 'Priority',
                'Extension'      => 'Extension',
                'Context'        => 'Context',
                'UniqueID'       => 'UniqueID',
                'Privilege'      => 'Privilege',
                'Channel'        => 'Channel',
            ],
            'Transfer'                   => [
                'TransferContext' => 'TransferContext',
                'TransferExten' => 'TransferExten',
                'TargetUniqueid' => 'TargetUniqueid',
                'UniqueID'      => 'UniqueID',
                'SIP-Callid'    => 'SIP-Callid',
                'TargetChannel' => 'TargetChannel',
                'Channel'       => 'Channel',
                'TransferType'  => 'TransferType',
                'TransferMethod' => 'TransferMethod',
                'Privilege'     => 'Privilege',
            ],
            'VoicemailUserEntryComplete' => [],
            'VoicemailUserEntry'         => [
                'VmContext'       => 'VmContext',
                'VoicemailBox'    => 'VoicemailBox',
                'Fullname'        => 'Fullname',
                'Email'           => 'Email',
                'Pager'           => 'Pager',
                'ServerEmail'     => 'ServerEmail',
                'MailCommand'     => 'MailCommand',
                'Language'        => 'Language',
                'Timezone'        => 'Timezone',
                'Callback'        => 'Callback',
                'DialOut'         => 'DialOut',
                'UniqueID'        => 'UniqueID',
                'ExitContext'     => 'ExitContext',
                'SayDurationMin'  => 'SayDurationMin',
                'SayEnvelope'     => 'SayEnvelope',
                'SayCID'          => 'SayCID',
                'AttachMessage'   => 'AttachMessage',
                'AttachmentFormat' => 'AttachmentFormat',
                'DeleteMessage'   => 'DeleteMessage',
                'VolumeGain'      => 'VolumeGain',
                'CanReview'       => 'CanReview',
                'CallOperator'    => 'CallOperator',
                'MaxMessageCount' => 'MaxMessageCount',
                'MaxMessageLength' => 'MaxMessageLength',
                'NewMessageCount' => 'NewMessageCount',
            ],
            'DBGetResponse'              => [
                'Family' => 'Family',
                'Key' => 'Key',
                'Val' => 'Val',
            ],
            'ParkedCallsComplete'        => [],
            'StatusComplete'             => ['Items' => 'Items'],
            'RegistrationsComplete'      => ['ListItems' => 'ListItems'],
            'DTMF'                       => [
                'Privilege' => 'Privilege',
                'UniqueID'  => 'UniqueID',
                'Channel'   => 'Channel',
                'Direction' => 'Direction',
                'End'       => 'End',
                'Begin'     => 'Begin',
                'Digit'     => 'Digit',
            ],
            'AGIExec'                    => [
                'Privilege'  => 'Privilege',
                'CommandId'  => 'CommandId',
                'SubEvent'   => 'SubEvent',
                'Channel'    => 'Channel',
                'Command'    => 'Command',
                'Result'     => 'Result',
                'ResultCode' => 'ResultCode',
            ],
            'VarSet'                     => [
                'Privilege' => 'Privilege',
                'Channel'   => 'Channel',
                'Variable'  => 'Variable',
                'Value'     => 'Value',
                'UniqueID'  => 'UniqueID',
            ],
            'Unlink'                     => [
                'Privilege' => 'Privilege',
                'CallerID1' => 'CallerID1',
                'CallerID2' => 'CallerID2',
                'UniqueID1' => 'UniqueID1',
                'UniqueID2' => 'UniqueID2',
                'Channel1'  => 'Channel1',
                'Channel2'  => 'Channel2',
            ],
            'Bridge'                     => [
                'Privilege'   => 'Privilege',
                'CallerID1'   => 'CallerID1',
                'CallerID2'   => 'CallerID2',
                'UniqueID1'   => 'UniqueID1',
                'UniqueID2'   => 'UniqueID2',
                'Channel1'    => 'Channel1',
                'Channel2'    => 'Channel2',
                'BridgeState' => 'BridgeStart',
                'BridgeType'  => 'BridgeType',
            ],
            'vgsm_sms_rx'                => [
                'Privilege'                        => 'Privilege',
                'X-SMS-Status-Report-Indication'   => 'X-SMS-Status-Report-Indication',
                'X-SMS-User-Data-Header-Indicator' => 'X-SMS-User-Data-Header-Indicator',
                'X-SMS-Reply-Path'                 => 'X-SMS-Reply-Path',
                'X-SMS-More-Messages-To-Send'      => 'X-SMS-More-Messages-To-Send',
                'X-SMS-SMCC-Number'                => 'X-SMS-SMCC-Number',
                'X-SMS-SMCC-TON'                   => 'X-SMS-SMCC-TON',
                'X-SMS-SMCC-NP'                    => 'X-SMS-SMCC-NP',
                'X-SMS-Sender-Number'              => 'X-SMS-Sender-Number',
                'X-SMS-Sender-TON'                 => 'X-SMS-Sender-TON',
                'X-SMS-Sender-NP'                  => 'X-SMS-Sender-NP',
                'X-SMS-Message-Type'               => 'X-SMS-Message-Type',
                'Content'                          => 'Content',
                'Date'                             => 'Date',
                'Content-Transfer-Encoding'        => 'ContentEncoding',
                'Content-Type'                     => 'ContentType',
                'MIME-Version'                     => 'MIME-Version',
                'Subject'                          => 'Subject',
                'From'                             => 'From',
                'Received'                         => 'Received',
            ],
            'vgsm_net_state'             => [
                'Privilege'               => 'Privilege',
                'X-vGSM-GSM-Registration' => 'X-vGSM-GSM-Registration',
            ],
            'vgsm_me_state'              => [
                'Privilege'                     => 'Privilege',
                'X-vGSM-ME-State-Change-Reason' => 'X-vGSM-ME-State-Change-Reason',
                'X-vGSM-ME-Old-State'           => 'X-vGSM-ME-Old-State',
                'X-vGSM-ME-State'               => 'X-vGSM-ME-State',
            ],
            'CEL'                        => [
                'AMAFlags'    => 'AMAFlags',
                'AccountCode' => 'AccountCode',
                'AppData'     => 'AppData',
                'Application' => 'Application',
                'CallerIDani' => 'CallerIDani',
                'CallerIDdnid' => 'CallerIDdnid',
                'CallerIDname' => 'CallerIDname',
                'CallerIDnum' => 'CallerIDnum',
                'CallerIDrdnis' => 'CallerIDrdnis',
                'Channel'     => 'Channel',
                'Context'     => 'Context',
                'Event'       => 'Event',
                'EventName'   => 'EventName',
                'EventTime'   => 'EventTime',
                'Exten'       => 'Exten',
                'Extra'       => 'Extra',
                'LinkedID'    => 'LinkedID',
                'Peer'        => 'Peer',
                'PeerAccount' => 'PeerAccount',
                'Privilege'   => 'Privilege',
                'Timestamp'   => 'Timestamp',
                'UniqueID'    => 'UniqueID',
                'Userfield'   => 'Userfield',
            ],
            'ParkedCall'                 => [
                'Privilege'          => 'Privilege',
                'Parkinglot'         => 'Parkinglot',
                'From'               => 'From',
                'Timeout'            => 'ParkingTimeout',
                'ConnectedLineNum'   => 'ParkeeConnectedLineNum',
                'ConnectedLineName'  => 'ParkeeConnectedLineName',
                'Channel'            => 'ParkeeChannel',
                'CallerIDNum'        => 'ParkeeCallerIDNum',
                'CallerIDName'       => 'ParkeeCallerIDName',
                'UniqueID'           => 'ParkeeUniqueid',
                'Exten'              => 'ParkingSpace',
                'ParkeeChannel'      => 'ParkeeChannel',
                'ParkeeChannelState' => 'ParkeeChannelState',
                'ParkeeChannelStateDesc' => 'ParkeeChannelStateDesc',
                'ParkeeCallerIDNum'  => 'ParkeeCallerIDNum',
                'ParkeeCallerIDName' => 'ParkeeCallerIDName',
                'ParkeeConnectedLineNum' => 'ParkeeConnectedLineNum',
                'ParkeeConnectedLineName' => 'ParkeeConnectedLineName',
                'ParkeeAccountCode'  => 'ParkeeAccountCode',
                'ParkeeContext'      => 'ParkeeContext',
                'ParkeeExten'        => 'ParkeeExten',
                'ParkeePriority'     => 'ParkeePriority',
                'ParkeeUniqueid'     => 'ParkeeUniqueid',
                'ParkerDialString'   => 'ParkerDialString',
                'ParkingSpace'       => 'ParkingSpace',
                'ParkingTimeout'     => 'ParkingTimeout',
                'ParkingDuration'    => 'ParkingDuration',
            ],
            'UnParkedCall'               => [
                'Privilege'               => 'Privilege',
                'Parkinglot'              => 'Parkinglot',
                'From'                    => 'RetrieverChannel',
                'ConnectedLineNum'        => 'ParkeeConnectedLineNum',
                'ConnectedLineName'       => 'ParkeeConnectedLineName',
                'Channel'                 => 'ParkeeChannel',
                'CallerIDNum'             => 'ParkeeCallerIDNum',
                'CallerIDName'            => 'ParkeeCallerIDName',
                'UniqueID'                => 'ParkeeUniqueid',
                'Exten'                   => 'ParkingSpace',
                'ParkeeChannel'           => 'ParkeeChannel',
                'ParkeeChannelState'      => 'ParkeeChannelState',
                'ParkeeChannelStateDesc'  => 'ParkeeChannelStateDesc',
                'ParkeeCallerIDNum'       => 'ParkeeCallerIDNum',
                'ParkeeCallerIDName'      => 'ParkeeCallerIDName',
                'ParkeeConnectedLineNum'  => 'ParkeeConnectedLineNum',
                'ParkeeConnectedLineName' => 'ParkeeConnectedLineName',
                'ParkeeAccountCode'       => 'ParkeeAccountCode',
                'ParkeeContext'           => 'ParkeeContext',
                'ParkeeExten'             => 'ParkeeExten',
                'ParkeePriority'          => 'ParkeePriority',
                'ParkeeUniqueid'          => 'ParkeeUniqueid',
                'ParkerDialString'        => 'ParkerDialString',
                'ParkingSpace'            => 'ParkingSpace',
                'ParkingTimeout'          => 'ParkingTimeout',
                'ParkingDuration'         => 'ParkingDuration',
                'ParkerChannel'           => 'ParkerChannel',
                'ParkerChannelState'      => 'ParkerChannelState',
                'ParkerChannelStateDesc'  => 'ParkerChannelStateDesc',
                'ParkerCallerIDNum'       => 'ParkerCallerIDNum',
                'ParkerCallerIDName'      => 'ParkerCallerIDName',
                'ParkerConnectedLineNum'  => 'ParkerConnectedLineNum',
                'ParkerConnectedLineName' => 'ParkerConnectedLineName',
                'ParkerAccountCode'       => 'ParkerAccountCode',
                'ParkerContext'           => 'ParkerContext',
                'ParkerExten'             => 'ParkerExten',
                'ParkerPriority'          => 'ParkerPriority',
                'ParkerUniqueid'          => 'ParkerUniqueid',
                'RetrieverChannel'        => 'RetrieverChannel',
                'RetrieverChannelState'   => 'RetrieverChannelState',
                'RetrieverChannelStateDesc' => 'RetrieverChannelStateDesc',
                'RetrieverCallerIDNum'    => 'RetrieverCallerIDNum',
                'RetrieverCallerIDName'   => 'RetrieverCallerIDName',
                'RetrieverConnectedLineNum' => 'RetrieverConnectedLineNum',
                'RetrieverConnectedLineName' => 'RetrieverConnectedLineName',
                'RetrieverAccountCode'    => 'RetrieverAccountCode',
                'RetrieverContext'        => 'RetrieverContext',
                'RetrieverExten'          => 'RetrieverExten',
                'RetrieverPriority'       => 'RetrieverPriority',
                'RetrieverUniqueid'       => 'RetrieverUniqueid',
            ],
            'Link'                       => [
                'Privilege' => 'Privilege',
                'CallerID1' => 'CallerID1',
                'CallerID2' => 'CallerID2',
                'UniqueID1' => 'UniqueID1',
                'UniqueID2' => 'UniqueID2',
                'Channel1' => 'Channel1',
                'Channel2' => 'Channel2',
            ],
            'AGIExecStart'               => [
                'Channel'      => 'Channel',
                'ChannelState' => 'ChannelState',
                'ChannelStateDesc' => 'ChannelStateDesc',
                'CallerIDNum'  => 'CallerIDNum',
                'CallerIDName' => 'CallerIDName',
                'ConnectedLineNum' => 'ConnectedLineNum',
                'ConnectedLineName' => 'ConnectedLineName',
                'AccountCode'  => 'AccountCode',
                'Context'      => 'Context',
                'Exten'        => 'Exten',
                'Priority'     => 'Priority',
                'Uniqueid'     => 'Uniqueid',
                'Command'      => 'Command',
                'CommandId'    => 'CommandId',
            ],
            'AGIExecEnd'                 => [
                'Channel'      => 'Channel',
                'ChannelState' => 'ChannelState',
                'ChannelStateDesc' => 'ChannelStateDesc',
                'CallerIDNum'  => 'CallerIDNum',
                'CallerIDName' => 'CallerIDName',
                'ConnectedLineNum' => 'ConnectedLineNum',
                'ConnectedLineName' => 'ConnectedLineName',
                'AccountCode'  => 'AccountCode',
                'Context'      => 'Context',
                'Exten'        => 'Exten',
                'Priority'     => 'Priority',
                'Uniqueid'     => 'Uniqueid',
                'Command'      => 'Command',
                'CommandId'    => 'CommandId',
                'ResultCode'   => 'ResultCode',
                'Result'       => 'Result',
            ],
            'AsyncAGIStart'              => [
                'Channel'      => 'Channel',
                'ChannelState' => 'ChannelState',
                'ChannelStateDesc' => 'ChannelStateDesc',
                'CallerIDNum'  => 'CallerIDNum',
                'CallerIDName' => 'CallerIDName',
                'ConnectedLineNum' => 'ConnectedLineNum',
                'ConnectedLineName' => 'ConnectedLineName',
                'AccountCode'  => 'AccountCode',
                'Context'      => 'Context',
                'Exten'        => 'Exten',
                'Priority'     => 'Priority',
                'Uniqueid'     => 'Uniqueid',
                'Env'          => 'Env',
            ],
            'AsyncAGIExec'               => [
                'Channel'      => 'Channel',
                'ChannelState' => 'ChannelState',
                'ChannelStateDesc' => 'ChannelStateDesc',
                'CallerIDNum'  => 'CallerIDNum',
                'CallerIDName' => 'CallerIDName',
                'ConnectedLineNum' => 'ConnectedLineNum',
                'ConnectedLineName' => 'ConnectedLineName',
                'AccountCode'  => 'AccountCode',
                'Context'      => 'Context',
                'Exten'        => 'Exten',
                'Priority'     => 'Priority',
                'Uniqueid'     => 'Uniqueid',
                'CommandID'    => 'CommandID',
                'Result'       => 'Result',
            ],
            'AsyncAGIEnd'                => [
                'Channel'      => 'Channel',
                'ChannelState' => 'ChannelState',
                'ChannelStateDesc' => 'ChannelStateDesc',
                'CallerIDNum'  => 'CallerIDNum',
                'CallerIDName' => 'CallerIDName',
                'ConnectedLineNum' => 'ConnectedLineNum',
                'ConnectedLineName' => 'ConnectedLineName',
                'AccountCode'  => 'AccountCode',
                'Context'      => 'Context',
                'Exten'        => 'Exten',
                'Priority'     => 'Priority',
                'Uniqueid'     => 'Uniqueid',
            ],
            'QueueCallerJoin'            => [
                'Channel'      => 'Channel',
                'ChannelState' => 'ChannelState',
                'ChannelStateDesc' => 'ChannelStateDesc',
                'CallerIDNum'  => 'CallerIDNum',
                'CallerIDName' => 'CallerIDName',
                'ConnectedLineNum' => 'ConnectedLineNum',
                'ConnectedLineName' => 'ConnectedLineName',
                'AccountCode'  => 'AccountCode',
                'Context'      => 'Context',
                'Exten'        => 'Exten',
                'Priority'     => 'Priority',
                'Uniqueid'     => 'Uniqueid',
                'Queue'        => 'Queue',
                'Position'     => 'Position',
                'Count'        => 'Count',
            ],
            'QueueCallerLeave'           => [
                'Channel'      => 'Channel',
                'ChannelState' => 'ChannelState',
                'ChannelStateDesc' => 'ChannelStateDesc',
                'CallerIDNum'  => 'CallerIDNum',
                'CallerIDName' => 'CallerIDName',
                'ConnectedLineNum' => 'ConnectedLineNum',
                'ConnectedLineName' => 'ConnectedLineName',
                'AccountCode'  => 'AccountCode',
                'Context'      => 'Context',
                'Exten'        => 'Exten',
                'Priority'     => 'Priority',
                'Uniqueid'     => 'Uniqueid',
                'Queue'        => 'Queue',
                'Count'        => 'Count',
                'Position'     => 'Position',
            ],
            'AttendedTransfer'           => [
                'Result'                          => 'Result',
                'OrigTransfererChannel'           => 'OrigTransfererChannel',
                'OrigTransfererChannelState'      => 'OrigTransfererChannelState',
                'OrigTransfererChannelStateDesc'  => 'OrigTransfererChannelStateDesc',
                'OrigTransfererCallerIDNum'       => 'OrigTransfererCallerIDNum',
                'OrigTransfererCallerIDName'      => 'OrigTransfererCallerIDName',
                'OrigTransfererConnectedLineNum'  => 'OrigTransfererConnectedLineNum',
                'OrigTransfererConnectedLineName' => 'OrigTransfererConnectedLineName',
                'OrigTransfererAccountCode'       => 'OrigTransfererAccountCode',
                'OrigTransfererContext'           => 'OrigTransfererContext',
                'OrigTransfererExten'             => 'OrigTransfererExten',
                'OrigTransfererPriority'          => 'OrigTransfererPriority',
                'OrigTransfererUniqueid'          => 'OrigTransfererUniqueid',
                'OrigBridgeUniqueid'              => 'OrigBridgeUniqueid',
                'OrigBridgeType'                  => 'OrigBridgeType',
                'OrigBridgeTechnology'            => 'OrigBridgeTechnology',
                'OrigBridgeCreator'               => 'OrigBridgeCreator',
                'OrigBridgeName'                  => 'OrigBridgeName',
                'OrigBridgeNumChannels'           => 'OrigBridgeNumChannels',
                'SecondTransfererChannel'         => 'SecondTransfererChannel',
                'SecondTransfererChannelState'    => 'SecondTransfererChannelState',
                'SecondTransfererChannelStateDesc' => 'SecondTransfererChannelStateDesc',
                'SecondTransfererCallerIDNum'     => 'SecondTransfererCallerIDNum',
                'SecondTransfererCallerIDName'    => 'SecondTransfererCallerIDName',
                'SecondTransfererConnectedLineNum' => 'SecondTransfererConnectedLineNum',
                'SecondTransfererConnectedLineName' => 'SecondTransfererConnectedLineName',
                'SecondTransfererAccountCode'     => 'SecondTransfererAccountCode',
                'SecondTransfererContext'         => 'SecondTransfererContext',
                'SecondTransfererExten'           => 'SecondTransfererExten',
                'SecondTransfererPriority'        => 'SecondTransfererPriority',
                'SecondTransfererUniqueid'        => 'SecondTransfererUniqueid',
                'SecondBridgeUniqueid'            => 'SecondBridgeUniqueid',
                'SecondBridgeType'                => 'SecondBridgeType',
                'SecondBridgeTechnology'          => 'SecondBridgeTechnology',
                'SecondBridgeCreator'             => 'SecondBridgeCreator',
                'SecondBridgeName'                => 'SecondBridgeName',
                'SecondBridgeNumChannels'         => 'SecondBridgeNumChannels',
                'DestType'                        => 'DestType',
                'DestBridgeUniqueid'              => 'DestBridgeUniqueid',
                'DestApp'                         => 'DestApp',
                'LocalOneChannel'                 => 'LocalOneChannel',
                'LocalOneChannelState'            => 'LocalOneChannelState',
                'LocalOneChannelStateDesc'        => 'LocalOneChannelStateDesc',
                'LocalOneCallerIDNum'             => 'LocalOneCallerIDNum',
                'LocalOneCallerIDName'            => 'LocalOneCallerIDName',
                'LocalOneConnectedLineNum'        => 'LocalOneConnectedLineNum',
                'LocalOneConnectedLineName'       => 'LocalOneConnectedLineName',
                'LocalOneAccountCode'             => 'LocalOneAccountCode',
                'LocalOneContext'                 => 'LocalOneContext',
                'LocalOneExten'                   => 'LocalOneExten',
                'LocalOnePriority'                => 'LocalOnePriority',
                'LocalOneUniqueid'                => 'LocalOneUniqueid',
                'LocalTwoChannel'                 => 'LocalTwoChannel',
                'LocalTwoChannelState'            => 'LocalTwoChannelState',
                'LocalTwoChannelStateDesc'        => 'LocalTwoChannelStateDesc',
                'LocalTwoCallerIDNum'             => 'LocalTwoCallerIDNum',
                'LocalTwoCallerIDName'            => 'LocalTwoCallerIDName',
                'LocalTwoConnectedLineNum'        => 'LocalTwoConnectedLineNum',
                'LocalTwoConnectedLineName'       => 'LocalTwoConnectedLineName',
                'LocalTwoAccountCode'             => 'LocalTwoAccountCode',
                'LocalTwoContext'                 => 'LocalTwoContext',
                'LocalTwoExten'                   => 'LocalTwoExten',
                'LocalTwoPriority'                => 'LocalTwoPriority',
                'LocalTwoUniqueid'                => 'LocalTwoUniqueid',
                'DestTransfererChannel'           => 'DestTransfererChannel',
                'TransfereeChannel'               => 'TransfereeChannel',
                'TransfereeChannelState'          => 'TransfereeChannelState',
                'TransfereeChannelStateDesc'      => 'TransfereeChannelStateDesc',
                'TransfereeCallerIDNum'           => 'TransfereeCallerIDNum',
                'TransfereeCallerIDName'          => 'TransfereeCallerIDName',
                'TransfereeConnectedLineNum'      => 'TransfereeConnectedLineNum',
                'TransfereeConnectedLineName'     => 'TransfereeConnectedLineName',
                'TransfereeAccountCode'           => 'TransfereeAccountCode',
                'TransfereeContext'               => 'TransfereeContext',
                'TransfereeExten'                 => 'TransfereeExten',
                'TransfereePriority'              => 'TransfereePriority',
                'TransfereeUniqueid'              => 'TransfereeUniqueid',
            ],
            'BlindTransfer'              => [
                'Result'                 => 'Result',
                'TransfererChannel'      => 'TransfererChannel',
                'TransfererChannelState' => 'TransfererChannelState',
                'TransfererChannelStateDesc' => 'TransfererChannelStateDesc',
                'TransfererCallerIDNum'  => 'TransfererCallerIDNum',
                'TransfererCallerIDName' => 'TransfererCallerIDName',
                'TransfererConnectedLineNum' => 'TransfererConnectedLineNum',
                'TransfererConnectedLineName' => 'TransfererConnectedLineName',
                'TransfererAccountCode'  => 'TransfererAccountCode',
                'TransfererContext'      => 'TransfererContext',
                'TransfererExten'        => 'TransfererExten',
                'TransfererPriority'     => 'TransfererPriority',
                'TransfererUniqueid'     => 'TransfererUniqueid',
                'TransfereeChannel'      => 'TransfereeChannel',
                'TransfereeChannelState' => 'TransfereeChannelState',
                'TransfereeChannelStateDesc' => 'TransfereeChannelStateDesc',
                'TransfereeCallerIDNum'  => 'TransfereeCallerIDNum',
                'TransfereeCallerIDName' => 'TransfereeCallerIDName',
                'TransfereeConnectedLineNum' => 'TransfereeConnectedLineNum',
                'TransfereeConnectedLineName' => 'TransfereeConnectedLineName',
                'TransfereeAccountCode'  => 'TransfereeAccountCode',
                'TransfereeContext'      => 'TransfereeContext',
                'TransfereeExten'        => 'TransfereeExten',
                'TransfereePriority'     => 'TransfereePriority',
                'TransfereeUniqueid'     => 'TransfereeUniqueid',
                'BridgeUniqueid'         => 'BridgeUniqueid',
                'BridgeType'             => 'BridgeType',
                'BridgeTechnology'       => 'BridgeTechnology',
                'BridgeCreator'          => 'BridgeCreator',
                'BridgeName'             => 'BridgeName',
                'BridgeNumChannels'      => 'BridgeNumChannels',
                'IsExternal'             => 'IsExternal',
                'Context'                => 'Context',
                'Extension'              => 'Extension',
            ],
            'DialBegin'                  => [
                'Channel'           => 'Channel',
                'ChannelState'      => 'ChannelState',
                'ChannelStateDesc'  => 'ChannelStateDesc',
                'CallerIDNum'       => 'CallerIDNum',
                'CallerIDName'      => 'CallerIDName',
                'ConnectedLineNum'  => 'ConnectedLineNum',
                'ConnectedLineName' => 'ConnectedLineName',
                'AccountCode'       => 'AccountCode',
                'Context'           => 'Context',
                'Exten'             => 'Exten',
                'Priority'          => 'Priority',
                'Uniqueid'          => 'Uniqueid',
                'DestChannel'       => 'DestChannel',
                'DestChannelState'  => 'DestChannelState',
                'DestChannelStateDesc' => 'DestChannelStateDesc',
                'DestCallerIDNum'   => 'DestCallerIDNum',
                'DestCallerIDName'  => 'DestCallerIDName',
                'DestConnectedLineNum' => 'DestConnectedLineNum',
                'DestConnectedLineName' => 'DestConnectedLineName',
                'DestAccountCode'   => 'DestAccountCode',
                'DestContext'       => 'DestContext',
                'DestExten'         => 'DestExten',
                'DestPriority'      => 'DestPriority',
                'DestUniqueid'      => 'DestUniqueid',
                'DialString'        => 'DialString',
            ],
            'DialEnd'                    => [
                'Channel'           => 'Channel',
                'ChannelState'      => 'ChannelState',
                'ChannelStateDesc'  => 'ChannelStateDesc',
                'CallerIDNum'       => 'CallerIDNum',
                'CallerIDName'      => 'CallerIDName',
                'ConnectedLineNum'  => 'ConnectedLineNum',
                'ConnectedLineName' => 'ConnectedLineName',
                'AccountCode'       => 'AccountCode',
                'Context'           => 'Context',
                'Exten'             => 'Exten',
                'Priority'          => 'Priority',
                'Uniqueid'          => 'Uniqueid',
                'DestChannel'       => 'DestChannel',
                'DestChannelState'  => 'DestChannelState',
                'DestChannelStateDesc' => 'DestChannelStateDesc',
                'DestCallerIDNum'   => 'DestCallerIDNum',
                'DestCallerIDName'  => 'DestCallerIDName',
                'DestConnectedLineNum' => 'DestConnectedLineNum',
                'DestConnectedLineName' => 'DestConnectedLineName',
                'DestAccountCode'   => 'DestAccountCode',
                'DestContext'       => 'DestContext',
                'DestExten'         => 'DestExten',
                'DestPriority'      => 'DestPriority',
                'DestUniqueid'      => 'DestUniqueid',
                'DialStatus'        => 'DialStatus',
            ],
            'DTMFBegin'                  => [
                'Channel'      => 'Channel',
                'ChannelState' => 'ChannelState',
                'ChannelStateDesc' => 'ChannelStateDesc',
                'CallerIDNum'  => 'CallerIDNum',
                'CallerIDName' => 'CallerIDName',
                'ConnectedLineNum' => 'ConnectedLineNum',
                'ConnectedLineName' => 'ConnectedLineName',
                'AccountCode'  => 'AccountCode',
                'Context'      => 'Context',
                'Exten'        => 'Exten',
                'Priority'     => 'Priority',
                'Uniqueid'     => 'Uniqueid',
                'Digit'        => 'Digit',
                'Direction'    => 'Direction',
            ],
            'DTMFEnd'                    => [
                'Channel'      => 'Channel',
                'ChannelState' => 'ChannelState',
                'ChannelStateDesc' => 'ChannelStateDesc',
                'CallerIDNum'  => 'CallerIDNum',
                'CallerIDName' => 'CallerIDName',
                'ConnectedLineNum' => 'ConnectedLineNum',
                'ConnectedLineName' => 'ConnectedLineName',
                'AccountCode'  => 'AccountCode',
                'Context'      => 'Context',
                'Exten'        => 'Exten',
                'Priority'     => 'Priority',
                'Uniqueid'     => 'Uniqueid',
                'Digit'        => 'Digit',
                'DurationMs'   => 'DurationMs',
                'Direction'    => 'Direction',
            ],
            'BridgeCreate'               => [
                'BridgeUniqueid' => 'BridgeUniqueid',
                'BridgeType'     => 'BridgeType',
                'BridgeTechnology' => 'BridgeTechnology',
                'BridgeCreator'  => 'BridgeCreator',
                'BridgeName'     => 'BridgeName',
                'BridgeNumChannels' => 'BridgeNumChannels',
            ],
            'BridgeDestroy'              => [
                'BridgeUniqueid' => 'BridgeUniqueid',
                'BridgeType'     => 'BridgeType',
                'BridgeTechnology' => 'BridgeTechnology',
                'BridgeCreator'  => 'BridgeCreator',
                'BridgeName'     => 'BridgeName',
                'BridgeNumChannels' => 'BridgeNumChannels',
            ],
            'BridgeEnter'                => [
                'BridgeUniqueid' => 'BridgeUniqueid',
                'BridgeType'     => 'BridgeType',
                'BridgeTechnology' => 'BridgeTechnology',
                'BridgeCreator'  => 'BridgeCreator',
                'BridgeName'     => 'BridgeName',
                'BridgeNumChannels' => 'BridgeNumChannels',
                'Channel'        => 'Channel',
                'ChannelState'   => 'ChannelState',
                'ChannelStateDesc' => 'ChannelStateDesc',
                'CallerIDNum'    => 'CallerIDNum',
                'CallerIDName'   => 'CallerIDName',
                'ConnectedLineNum' => 'ConnectedLineNum',
                'ConnectedLineName' => 'ConnectedLineName',
                'AccountCode'    => 'AccountCode',
                'Context'        => 'Context',
                'Exten'          => 'Exten',
                'Priority'       => 'Priority',
                'Uniqueid'       => 'Uniqueid',
                'SwapUniqueid'   => 'SwapUniqueid',
            ],
            'BridgeLeave'                => [
                'BridgeUniqueid' => 'BridgeUniqueid',
                'BridgeType'     => 'BridgeType',
                'BridgeTechnology' => 'BridgeTechnology',
                'BridgeCreator'  => 'BridgeCreator',
                'BridgeName'     => 'BridgeName',
                'BridgeNumChannels' => 'BridgeNumChannels',
                'Channel'        => 'Channel',
                'ChannelState'   => 'ChannelState',
                'ChannelStateDesc' => 'ChannelStateDesc',
                'CallerIDNum'    => 'CallerIDNum',
                'CallerIDName'   => 'CallerIDName',
                'ConnectedLineNum' => 'ConnectedLineNum',
                'ConnectedLineName' => 'ConnectedLineName',
                'AccountCode'    => 'AccountCode',
                'Context'        => 'Context',
                'Exten'          => 'Exten',
                'Priority'       => 'Priority',
                'Uniqueid'       => 'Uniqueid',
            ],
            'MusicOnHoldStart'           => [
                'Channel'      => 'Channel',
                'ChannelState' => 'ChannelState',
                'ChannelStateDesc' => 'ChannelStateDesc',
                'CallerIDNum'  => 'CallerIDNum',
                'CallerIDName' => 'CallerIDName',
                'ConnectedLineNum' => 'ConnectedLineNum',
                'ConnectedLineName' => 'ConnectedLineName',
                'AccountCode'  => 'AccountCode',
                'Context'      => 'Context',
                'Exten'        => 'Exten',
                'Priority'     => 'Priority',
                'Uniqueid'     => 'Uniqueid',
                'Class'        => 'Class',
            ],
            'MusicOnHoldStop'            => [
                'Channel'      => 'Channel',
                'ChannelState' => 'ChannelState',
                'ChannelStateDesc' => 'ChannelStateDesc',
                'CallerIDNum'  => 'CallerIDNum',
                'CallerIDName' => 'CallerIDName',
                'ConnectedLineNum' => 'ConnectedLineNum',
                'ConnectedLineName' => 'ConnectedLineName',
                'AccountCode'  => 'AccountCode',
                'Context'      => 'Context',
                'Exten'        => 'Exten',
                'Priority'     => 'Priority',
                'Uniqueid'     => 'Uniqueid',
            ],
            'ConfbridgeStart'            => [
                'Conference'     => 'Conference',
                'BridgeUniqueid' => 'BridgeUniqueid',
                'BridgeType'     => 'BridgeType',
                'BridgeTechnology' => 'BridgeTechnology',
                'BridgeCreator'  => 'BridgeCreator',
                'BridgeName'     => 'BridgeName',
                'BridgeNumChannels' => 'BridgeNumChannels',
            ],
            'ConfbridgeEnd'              => [
                'Conference'     => 'Conference',
                'BridgeUniqueid' => 'BridgeUniqueid',
                'BridgeType'     => 'BridgeType',
                'BridgeTechnology' => 'BridgeTechnology',
                'BridgeCreator'  => 'BridgeCreator',
                'BridgeName'     => 'BridgeName',
                'BridgeNumChannels' => 'BridgeNumChannels',
            ],
            'ConfbridgeJoin'             => [
                'Conference'     => 'Conference',
                'BridgeUniqueid' => 'BridgeUniqueid',
                'BridgeType'     => 'BridgeType',
                'BridgeTechnology' => 'BridgeTechnology',
                'BridgeCreator'  => 'BridgeCreator',
                'BridgeName'     => 'BridgeName',
                'BridgeNumChannels' => 'BridgeNumChannels',
                'Channel'        => 'Channel',
                'ChannelState'   => 'ChannelState',
                'ChannelStateDesc' => 'ChannelStateDesc',
                'CallerIDNum'    => 'CallerIDNum',
                'CallerIDName'   => 'CallerIDName',
                'ConnectedLineNum' => 'ConnectedLineNum',
                'ConnectedLineName' => 'ConnectedLineName',
                'AccountCode'    => 'AccountCode',
                'Context'        => 'Context',
                'Exten'          => 'Exten',
                'Priority'       => 'Priority',
                'Uniqueid'       => 'Uniqueid',
                'Linkedid'       => 'Linkedid',
                'Admin'          => 'Admin',
            ],
            'ConfbridgeLeave'            => [
                'Conference'     => 'Conference',
                'BridgeUniqueid' => 'BridgeUniqueid',
                'BridgeType'     => 'BridgeType',
                'BridgeTechnology' => 'BridgeTechnology',
                'BridgeCreator'  => 'BridgeCreator',
                'BridgeName'     => 'BridgeName',
                'BridgeNumChannels' => 'BridgeNumChannels',
                'Channel'        => 'Channel',
                'ChannelState'   => 'ChannelState',
                'ChannelStateDesc' => 'ChannelStateDesc',
                'CallerIDNum'    => 'CallerIDNum',
                'CallerIDName'   => 'CallerIDName',
                'ConnectedLineNum' => 'ConnectedLineNum',
                'ConnectedLineName' => 'ConnectedLineName',
                'AccountCode'    => 'AccountCode',
                'Context'        => 'Context',
                'Exten'          => 'Exten',
                'Priority'       => 'Priority',
                'Uniqueid'       => 'Uniqueid',
                'Linkedid'       => 'Linkedid',
                'Admin'          => 'Admin',
            ],
            'ConfbridgeMute'             => [
                'Conference'     => 'Conference',
                'BridgeUniqueid' => 'BridgeUniqueid',
                'BridgeType'     => 'BridgeType',
                'BridgeTechnology' => 'BridgeTechnology',
                'BridgeCreator'  => 'BridgeCreator',
                'BridgeName'     => 'BridgeName',
                'BridgeNumChannels' => 'BridgeNumChannels',
                'Channel'        => 'Channel',
                'ChannelState'   => 'ChannelState',
                'ChannelStateDesc' => 'ChannelStateDesc',
                'CallerIDNum'    => 'CallerIDNum',
                'CallerIDName'   => 'CallerIDName',
                'ConnectedLineNum' => 'ConnectedLineNum',
                'ConnectedLineName' => 'ConnectedLineName',
                'AccountCode'    => 'AccountCode',
                'Context'        => 'Context',
                'Exten'          => 'Exten',
                'Priority'       => 'Priority',
                'Uniqueid'       => 'Uniqueid',
                'Linkedid'       => 'Linkedid',
                'Admin'          => 'Admin',
            ],
            'ConfbridgeUnmute'           => [
                'Conference'     => 'Conference',
                'BridgeUniqueid' => 'BridgeUniqueid',
                'BridgeType'     => 'BridgeType',
                'BridgeTechnology' => 'BridgeTechnology',
                'BridgeCreator'  => 'BridgeCreator',
                'BridgeName'     => 'BridgeName',
                'BridgeNumChannels' => 'BridgeNumChannels',
                'Channel'        => 'Channel',
                'ChannelState'   => 'ChannelState',
                'ChannelStateDesc' => 'ChannelStateDesc',
                'CallerIDNum'    => 'CallerIDNum',
                'CallerIDName'   => 'CallerIDName',
                'ConnectedLineNum' => 'ConnectedLineNum',
                'ConnectedLineName' => 'ConnectedLineName',
                'AccountCode'    => 'AccountCode',
                'Context'        => 'Context',
                'Exten'          => 'Exten',
                'Priority'       => 'Priority',
                'Uniqueid'       => 'Uniqueid',
                'Linkedid'       => 'Linkedid',
                'Admin'          => 'Admin',
            ],
            'ConfbridgeTalking'          => [
                'Conference'     => 'Conference',
                'BridgeUniqueid' => 'BridgeUniqueid',
                'BridgeType'     => 'BridgeType',
                'BridgeTechnology' => 'BridgeTechnology',
                'BridgeCreator'  => 'BridgeCreator',
                'BridgeName'     => 'BridgeName',
                'BridgeNumChannels' => 'BridgeNumChannels',
                'Channel'        => 'Channel',
                'ChannelState'   => 'ChannelState',
                'ChannelStateDesc' => 'ChannelStateDesc',
                'CallerIDNum'    => 'CallerIDNum',
                'CallerIDName'   => 'CallerIDName',
                'ConnectedLineNum' => 'ConnectedLineNum',
                'ConnectedLineName' => 'ConnectedLineName',
                'AccountCode'    => 'AccountCode',
                'Context'        => 'Context',
                'Exten'          => 'Exten',
                'Priority'       => 'Priority',
                'Uniqueid'       => 'Uniqueid',
                'Linkedid'       => 'Linkedid',
                'TalkingStatus'  => 'TalkingStatus',
                'Admin'          => 'Admin',
            ],
            'ConfbridgeList'             => [
                'Conference' => 'Conference',
                'Channel'    => 'Channel',
                'CallerIDNum' => 'CallerIDNum',
                'CallerIDName' => 'CallerIDName',
                'MarkedUser' => 'MarkedUser',
                'WaitMarked' => 'WaitMarked',
                'EndMarked'  => 'EndMarked',
                'Waiting'    => 'Waiting',
                'Muted'      => 'Muted',
                'AnsweredTime' => 'AnsweredTime',
                'Admin'      => 'Admin',
            ],
            'ConfbridgeListComplete'     => ['ListItems' => 'ListItems'],
            'BridgeInfoChannel'          => [
                'Channel'      => 'Channel',
                'ChannelState' => 'ChannelState',
                'ChannelStateDesc' => 'ChannelStateDesc',
                'CallerIDNum'  => 'CallerIDNum',
                'CallerIDName' => 'CallerIDName',
                'ConnectedLineNum' => 'ConnectedLineNum',
                'ConnectedLineName' => 'ConnectedLineName',
                'AccountCode'  => 'AccountCode',
                'Context'      => 'Context',
                'Exten'        => 'Exten',
                'Priority'     => 'Priority',
                'Uniqueid'     => 'Uniqueid',
                'Linkedid'     => 'Linkedid',
            ],
            'BridgeInfoComplete'         => [
                'BridgeUniqueid'   => 'BridgeUniqueid',
                'BridgeType'       => 'BridgeType',
                'BridgeTechnology' => 'BridgeTechnology',
                'BridgeCreator'    => 'BridgeCreator',
                'BridgeName'       => 'BridgeName',
                'BridgeNumChannels' => 'BridgeNumChannels',
                'BridgeVideoSourceMode' => 'BridgeVideoSourceMode',
                'BridgeVideoSource' => 'BridgeVideoSource',
            ],
        ];
        $eventGetters          = [
            'UserEvent'                 => [
                'UserEvent' => 'UserEventName',
            ],
            'AsyncAGI'                  => [
                'Env' => 'Environment',
            ],
            'Agents'                    => [
                'LoggedInChan' => 'Channel',
            ],
            'ExtensionStatus'           => [
                'Exten' => 'Extension',
            ],
            'Hangup'                    => [
                'cause-txt' => 'CauseText',
            ],
            'ListDialplan'              => [
                'AppData' => 'ApplicationData',
            ],
            'NewCallerid'               => [
                'CID-CallingPres' => 'CallerIdPres',
            ],
            'Newchannel'                => ['Exten' => 'Extension'],
            'Newexten'                  => [
                'AppData' => 'ApplicationData',
            ],
            'QueueMemberStatus'         => [
                'Paused' => 'Pause',
            ],
            'QueueMember'               => [
                'Name' => 'MemberName',
            ],
            'AGIExec'                   => [],
            'Transfer'                  => [
                'SIP-Callid' => 'SipCallID',
            ],
            'VoicemailUserEntry'        => [
                'VmContext' => 'VoicemailContext',
            ],
            'PeerEntry'                 => ['ChanObjectType' => 'ChannelObjectType'],
            'VarSet'                    => ['Variable' => 'VariableName'],
            'StatusComplete'            => ['Items' => 'ListItems'],
            'DBGetResponse'             => ['Key' => 'KeyName', 'Val' => 'Value'],
            'vgsm_sms_rx'               => [
                'X-SMS-Status-Report-Indication'   => 'StatusReportIndication',
                'X-SMS-User-Data-Header-Indicator' => 'DataHeaderIndicator',
                'X-SMS-Reply-Path'                 => 'ReplyPath',
                'X-SMS-More-Messages-To-Send'      => 'MoreMessagesToSend',
                'X-SMS-SMCC-Number'                => 'SMCCNumber',
                'X-SMS-SMCC-TON'                   => 'SMCCTON',
                'X-SMS-SMCC-NP'                    => 'SMCCNP',
                'X-SMS-Sender-Number'              => 'SenderNumber',
                'X-SMS-Sender-TON'                 => 'SenderTON',
                'X-SMS-Sender-NP'                  => 'SenderNP',
                'X-SMS-Message-Type'               => 'MessageType',
                'Content-Transfer-Encoding'        => 'ContentEncoding',
                'Content-Type'                     => 'ContentType',
                'MIME-Version'                     => 'MIMEVersion',
            ],
            'DAHDIShowChannelsComplete' => ['items' => 'ListItems'],
            'vgsm_net_state'            => ['X-vGSM-GSM-Registration' => 'State'],
            'vgsm_me_state'             => [
                'X-vGSM-ME-State-Change-Reason' => 'Reason',
                'X-vGSM-ME-Old-State'           => 'OldState',
                'X-vGSM-ME-State'               => 'State',
            ],
            'ParkedCall'                => ['Exten' => 'Extension'],
            'UnParkedCall'              => ['Exten' => 'Extension'],
            'AGIExecStart'              => [

            ],
        ];
        foreach ($eventNames as $eventName) {
            $this->testEvent($eventName, $eventGetters, $eventValues[$eventName], $eventTranslatedValues);
        }
    }

    /**
     * @param string                               $eventName
     * @param array<string, array<string, string>> $getters
     * @param array<string, int|string>            $values
     * @param array<string, array<string, true>>   $translatedValues
     *
     * @throws \PAMI\Client\Exception\ClientException
     */
    private function testEvent(string $eventName, array $getters, array $values, array $translatedValues): void
    {
        $eventClass = "PAMI\\Message\\Event\\" . str_replace(' ', '',
                ucwords(str_replace('_', ' ', $eventName))) . 'Event';

        $options = [
            'host'         => '2.3.4.5',
            'scheme'       => 'tcp://',
            'port'         => 9999,
            'username'     => 'asd',
            'secret'       => 'asd',
            'connect_timeout' => 10,
            'read_timeout' => 20,
        ];
        $write   =
            "action: Login\r\n" .
            "actionid: " . $this->microTime . "\r\n" .
            "username: asd\r\n" .
            "secret: asd\r\n\r\n";

        $stream = Mockery::mock(Stream::class);

        $client = Mockery::mock(ClientImpl::class, [$options]);
        $client->makePartial();
        $client->shouldAllowMockingProtectedMethods();

        $client->shouldReceive('makeStream')->andReturn($stream);

        $stream->shouldReceive('getLine')
            ->once()
            ->andReturn('Asterisk 1234');

        $stream->shouldReceive('write')
            ->once()
            ->with($write)
            ->andReturn(strlen($write));

        $stream->shouldReceive('read')
            ->times(5)
            ->andReturn(
                "Asterisk Call Manager/1.1\r\n",
                "Response: Success\r\n",
                "ActionID: " . $this->microTime . "\r\n",
                "Message: Authentication accepted\r\n",
                "\r\n\r\n"
            );

        $stream->shouldReceive('endOfFile')
            ->andReturnFalse();

        $stream->shouldReceive('setBlocking')
            ->once()
            ->with(false);

        $stream->shouldReceive('isConnected')
            ->andReturnTrue();

        $client->open();

        $client->registerEventListener(new SomeListenerClass);

        $message   = [];
        $message[] = 'Event: ' . $eventName . "\r\n";
        foreach ($values as $key => $value) {
            $message[] = $key . ': ' . $value . "\r\n";
        }
        $message[] = "\r\n";

        $stream->shouldReceive('read')->andReturn(...$message);

        for ($i = 0; $i < count($message); $i++) {
            $client->process();
        }

        $event = SomeListenerClass::$event;
        foreach ($values as $key => $value) {
            if (isset($getters[$eventName][$key])) {
                $methodName = 'get' . $getters[$eventName][$key];
            } else {
                $methodName = 'get' . $key;
            }
            if (isset($translatedValues[$eventName][$key])) {
                $value = $translatedValues[$eventName][$key];
            }

            $this->assertTrue(
                method_exists($event, $methodName),
                sprintf(
                    "Method %s doesn't exist in event %s. Data: %s. Messages:\r\n%s",
                    $methodName,
                    get_class($event),
                    var_export(func_get_args(), true),
                    implode("", $message)
                )
            );

            $this->assertEquals($event->$methodName(), $value, $eventName);
        }

        $this->assertEquals($eventClass, get_class($event));
    }
}
